// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol_message.proto
// Protobuf Java Version: 4.32.0-dev

package com.wsg.protocol.protobuf;

@com.google.protobuf.Generated
public final class ProtocolMessage {
  private ProtocolMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "-dev",
      ProtocolMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wsg.gateway.protocol.PackMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes wsgId = 1;</code>
     * @return The wsgId.
     */
    com.google.protobuf.ByteString getWsgId();

    /**
     * <code>bytes connId = 2;</code>
     * @return The connId.
     */
    com.google.protobuf.ByteString getConnId();

    /**
     * <code>bytes action = 3;</code>
     * @return The action.
     */
    com.google.protobuf.ByteString getAction();

    /**
     * <code>bytes appId = 4;</code>
     * @return The appId.
     */
    com.google.protobuf.ByteString getAppId();

    /**
     * <code>bytes msg = 5;</code>
     * @return The msg.
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * <pre>
   * use bytes instead of string to skip utf8-validate
   * </pre>
   *
   * Protobuf type {@code wsg.gateway.protocol.PackMessage}
   */
  public static final class PackMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:wsg.gateway.protocol.PackMessage)
      PackMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "-dev",
        PackMessage.class.getName());
    }
    // Use PackMessage.newBuilder() to construct.
    private PackMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PackMessage() {
      wsgId_ = com.google.protobuf.ByteString.EMPTY;
      connId_ = com.google.protobuf.ByteString.EMPTY;
      action_ = com.google.protobuf.ByteString.EMPTY;
      appId_ = com.google.protobuf.ByteString.EMPTY;
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wsg.protocol.protobuf.ProtocolMessage.internal_static_wsg_gateway_protocol_PackMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wsg.protocol.protobuf.ProtocolMessage.internal_static_wsg_gateway_protocol_PackMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.class, com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.Builder.class);
    }

    public static final int WSGID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString wsgId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes wsgId = 1;</code>
     * @return The wsgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getWsgId() {
      return wsgId_;
    }

    public static final int CONNID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString connId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes connId = 2;</code>
     * @return The connId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getConnId() {
      return connId_;
    }

    public static final int ACTION_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString action_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes action = 3;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAction() {
      return action_;
    }

    public static final int APPID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString appId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes appId = 4;</code>
     * @return The appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAppId() {
      return appId_;
    }

    public static final int MSG_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes msg = 5;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!wsgId_.isEmpty()) {
        output.writeBytes(1, wsgId_);
      }
      if (!connId_.isEmpty()) {
        output.writeBytes(2, connId_);
      }
      if (!action_.isEmpty()) {
        output.writeBytes(3, action_);
      }
      if (!appId_.isEmpty()) {
        output.writeBytes(4, appId_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(5, msg_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!wsgId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, wsgId_);
      }
      if (!connId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, connId_);
      }
      if (!action_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, action_);
      }
      if (!appId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, appId_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, msg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wsg.protocol.protobuf.ProtocolMessage.PackMessage)) {
        return super.equals(obj);
      }
      com.wsg.protocol.protobuf.ProtocolMessage.PackMessage other = (com.wsg.protocol.protobuf.ProtocolMessage.PackMessage) obj;

      if (!getWsgId()
          .equals(other.getWsgId())) return false;
      if (!getConnId()
          .equals(other.getConnId())) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (!getAppId()
          .equals(other.getAppId())) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WSGID_FIELD_NUMBER;
      hash = (53 * hash) + getWsgId().hashCode();
      hash = (37 * hash) + CONNID_FIELD_NUMBER;
      hash = (53 * hash) + getConnId().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wsg.protocol.protobuf.ProtocolMessage.PackMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * use bytes instead of string to skip utf8-validate
     * </pre>
     *
     * Protobuf type {@code wsg.gateway.protocol.PackMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wsg.gateway.protocol.PackMessage)
        com.wsg.protocol.protobuf.ProtocolMessage.PackMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wsg.protocol.protobuf.ProtocolMessage.internal_static_wsg_gateway_protocol_PackMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wsg.protocol.protobuf.ProtocolMessage.internal_static_wsg_gateway_protocol_PackMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.class, com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.Builder.class);
      }

      // Construct using com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        wsgId_ = com.google.protobuf.ByteString.EMPTY;
        connId_ = com.google.protobuf.ByteString.EMPTY;
        action_ = com.google.protobuf.ByteString.EMPTY;
        appId_ = com.google.protobuf.ByteString.EMPTY;
        msg_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wsg.protocol.protobuf.ProtocolMessage.internal_static_wsg_gateway_protocol_PackMessage_descriptor;
      }

      @java.lang.Override
      public com.wsg.protocol.protobuf.ProtocolMessage.PackMessage getDefaultInstanceForType() {
        return com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.wsg.protocol.protobuf.ProtocolMessage.PackMessage build() {
        com.wsg.protocol.protobuf.ProtocolMessage.PackMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wsg.protocol.protobuf.ProtocolMessage.PackMessage buildPartial() {
        com.wsg.protocol.protobuf.ProtocolMessage.PackMessage result = new com.wsg.protocol.protobuf.ProtocolMessage.PackMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.wsg.protocol.protobuf.ProtocolMessage.PackMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.wsgId_ = wsgId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.connId_ = connId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.appId_ = appId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.msg_ = msg_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wsg.protocol.protobuf.ProtocolMessage.PackMessage) {
          return mergeFrom((com.wsg.protocol.protobuf.ProtocolMessage.PackMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wsg.protocol.protobuf.ProtocolMessage.PackMessage other) {
        if (other == com.wsg.protocol.protobuf.ProtocolMessage.PackMessage.getDefaultInstance()) return this;
        if (!other.getWsgId().isEmpty()) {
          setWsgId(other.getWsgId());
        }
        if (!other.getConnId().isEmpty()) {
          setConnId(other.getConnId());
        }
        if (!other.getAction().isEmpty()) {
          setAction(other.getAction());
        }
        if (!other.getAppId().isEmpty()) {
          setAppId(other.getAppId());
        }
        if (!other.getMsg().isEmpty()) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                wsgId_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                connId_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                action_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                appId_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                msg_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString wsgId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes wsgId = 1;</code>
       * @return The wsgId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getWsgId() {
        return wsgId_;
      }
      /**
       * <code>bytes wsgId = 1;</code>
       * @param value The wsgId to set.
       * @return This builder for chaining.
       */
      public Builder setWsgId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        wsgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes wsgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wsgId_ = getDefaultInstance().getWsgId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString connId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes connId = 2;</code>
       * @return The connId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getConnId() {
        return connId_;
      }
      /**
       * <code>bytes connId = 2;</code>
       * @param value The connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        connId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes connId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        connId_ = getDefaultInstance().getConnId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString action_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes action = 3;</code>
       * @return The action.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAction() {
        return action_;
      }
      /**
       * <code>bytes action = 3;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        action_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes action = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString appId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes appId = 4;</code>
       * @return The appId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAppId() {
        return appId_;
      }
      /**
       * <code>bytes appId = 4;</code>
       * @param value The appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        appId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes appId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg = 5;</code>
       * @return The msg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>bytes msg = 5;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        msg_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wsg.gateway.protocol.PackMessage)
    }

    // @@protoc_insertion_point(class_scope:wsg.gateway.protocol.PackMessage)
    private static final com.wsg.protocol.protobuf.ProtocolMessage.PackMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wsg.protocol.protobuf.ProtocolMessage.PackMessage();
    }

    public static com.wsg.protocol.protobuf.ProtocolMessage.PackMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackMessage>
        PARSER = new com.google.protobuf.AbstractParser<PackMessage>() {
      @java.lang.Override
      public PackMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PackMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wsg.protocol.protobuf.ProtocolMessage.PackMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wsg_gateway_protocol_PackMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wsg_gateway_protocol_PackMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protocol_message.proto\022\024wsg.gateway.pr" +
      "otocol\"X\n\013PackMessage\022\r\n\005wsgId\030\001 \001(\014\022\016\n\006" +
      "connId\030\002 \001(\014\022\016\n\006action\030\003 \001(\014\022\r\n\005appId\030\004 " +
      "\001(\014\022\013\n\003msg\030\005 \001(\014B\033\n\031com.wsg.protocol.pro" +
      "tobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wsg_gateway_protocol_PackMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wsg_gateway_protocol_PackMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_wsg_gateway_protocol_PackMessage_descriptor,
        new java.lang.String[] { "WsgId", "ConnId", "Action", "AppId", "Msg", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
