name: CMake Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt update
          sudo apt install build-essential cmake
          sudo apt install libgtest-dev libgmock-dev
          sudo apt install libmosquitto-dev
          sudo apt install libdbus-1-dev
      - uses: actions/checkout@v3
      - name: Build
        run: cmake -B build && cmake --build build
      - name: Test
        run: find ./build -name *_test -exec {} \;
