// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol_message.proto
// Protobuf C++ Version: 6.32.0-dev

#include "protocol_message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace wsg {
namespace gateway {
namespace protocol {

inline constexpr PackMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        wsgid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        connid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        appid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PackMessage::PackMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PackMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PackMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PackMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PackMessageDefaultTypeInternal() {}
  union {
    PackMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PackMessageDefaultTypeInternal _PackMessage_default_instance_;
}  // namespace protocol
}  // namespace gateway
}  // namespace wsg
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_protocol_5fmessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_protocol_5fmessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_protocol_5fmessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::wsg::gateway::protocol::PackMessage, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::wsg::gateway::protocol::PackMessage, _impl_.wsgid_),
        PROTOBUF_FIELD_OFFSET(::wsg::gateway::protocol::PackMessage, _impl_.connid_),
        PROTOBUF_FIELD_OFFSET(::wsg::gateway::protocol::PackMessage, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::wsg::gateway::protocol::PackMessage, _impl_.appid_),
        PROTOBUF_FIELD_OFFSET(::wsg::gateway::protocol::PackMessage, _impl_.msg_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::wsg::gateway::protocol::PackMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::wsg::gateway::protocol::_PackMessage_default_instance_._instance,
};
const char descriptor_table_protodef_protocol_5fmessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026protocol_message.proto\022\024wsg.gateway.pr"
    "otocol\"X\n\013PackMessage\022\r\n\005wsgId\030\001 \001(\014\022\016\n\006"
    "connId\030\002 \001(\014\022\016\n\006action\030\003 \001(\014\022\r\n\005appId\030\004 "
    "\001(\014\022\013\n\003msg\030\005 \001(\014B\033\n\031com.wsg.protocol.pro"
    "tobufb\006proto3"
};
static ::absl::once_flag descriptor_table_protocol_5fmessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protocol_5fmessage_2eproto = {
    false,
    false,
    173,
    descriptor_table_protodef_protocol_5fmessage_2eproto,
    "protocol_message.proto",
    &descriptor_table_protocol_5fmessage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protocol_5fmessage_2eproto::offsets,
    file_level_enum_descriptors_protocol_5fmessage_2eproto,
    file_level_service_descriptors_protocol_5fmessage_2eproto,
};
namespace wsg {
namespace gateway {
namespace protocol {
// ===================================================================

class PackMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PackMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PackMessage, _impl_._has_bits_);
};

PackMessage::PackMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PackMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wsg.gateway.protocol.PackMessage)
}
PROTOBUF_NDEBUG_INLINE PackMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::wsg::gateway::protocol::PackMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        wsgid_(arena, from.wsgid_),
        connid_(arena, from.connid_),
        action_(arena, from.action_),
        appid_(arena, from.appid_),
        msg_(arena, from.msg_) {}

PackMessage::PackMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PackMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PackMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PackMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:wsg.gateway.protocol.PackMessage)
}
PROTOBUF_NDEBUG_INLINE PackMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        wsgid_(arena),
        connid_(arena),
        action_(arena),
        appid_(arena),
        msg_(arena) {}

inline void PackMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PackMessage::~PackMessage() {
  // @@protoc_insertion_point(destructor:wsg.gateway.protocol.PackMessage)
  SharedDtor(*this);
}
inline void PackMessage::SharedDtor(MessageLite& self) {
  PackMessage& this_ = static_cast<PackMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.wsgid_.Destroy();
  this_._impl_.connid_.Destroy();
  this_._impl_.action_.Destroy();
  this_._impl_.appid_.Destroy();
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PackMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PackMessage(arena);
}
constexpr auto PackMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PackMessage),
                                            alignof(PackMessage));
}
constexpr auto PackMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PackMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PackMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PackMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PackMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PackMessage>(), &PackMessage::ByteSizeLong,
              &PackMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PackMessage, _impl_._cached_size_),
          false,
      },
      &PackMessage::kDescriptorMethods,
      &descriptor_table_protocol_5fmessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PackMessage_class_data_ =
        PackMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PackMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PackMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PackMessage_class_data_.tc_table);
  return PackMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
PackMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PackMessage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PackMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wsg::gateway::protocol::PackMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes wsgId = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.wsgid_)}},
    // bytes connId = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.connid_)}},
    // bytes action = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.action_)}},
    // bytes appId = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 3, 0, PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.appid_)}},
    // bytes msg = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 4, 0, PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.msg_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes wsgId = 1;
    {PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.wsgid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes connId = 2;
    {PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.connid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes action = 3;
    {PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.action_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes appId = 4;
    {PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.appid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes msg = 5;
    {PROTOBUF_FIELD_OFFSET(PackMessage, _impl_.msg_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PackMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:wsg.gateway.protocol.PackMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.wsgid_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.connid_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _impl_.action_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _impl_.appid_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      _impl_.msg_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PackMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PackMessage& this_ = static_cast<const PackMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PackMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PackMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:wsg.gateway.protocol.PackMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes wsgId = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_wsgid().empty()) {
      const ::std::string& _s = this_._internal_wsgid();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes connId = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_connid().empty()) {
      const ::std::string& _s = this_._internal_connid();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // bytes action = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (!this_._internal_action().empty()) {
      const ::std::string& _s = this_._internal_action();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // bytes appId = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008U) != 0) {
    if (!this_._internal_appid().empty()) {
      const ::std::string& _s = this_._internal_appid();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  // bytes msg = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010U) != 0) {
    if (!this_._internal_msg().empty()) {
      const ::std::string& _s = this_._internal_msg();
      target = stream->WriteBytesMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wsg.gateway.protocol.PackMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PackMessage::ByteSizeLong(const MessageLite& base) {
  const PackMessage& this_ = static_cast<const PackMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PackMessage::ByteSizeLong() const {
  const PackMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:wsg.gateway.protocol.PackMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fU) != 0) {
    // bytes wsgId = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_wsgid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_wsgid());
      }
    }
    // bytes connId = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_connid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_connid());
      }
    }
    // bytes action = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (!this_._internal_action().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_action());
      }
    }
    // bytes appId = 4;
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (!this_._internal_appid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_appid());
      }
    }
    // bytes msg = 5;
    if ((cached_has_bits & 0x00000010U) != 0) {
      if (!this_._internal_msg().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_msg());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PackMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PackMessage*>(&to_msg);
  auto& from = static_cast<const PackMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wsg.gateway.protocol.PackMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_wsgid().empty()) {
        _this->_internal_set_wsgid(from._internal_wsgid());
      } else {
        if (_this->_impl_.wsgid_.IsDefault()) {
          _this->_internal_set_wsgid("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_connid().empty()) {
        _this->_internal_set_connid(from._internal_connid());
      } else {
        if (_this->_impl_.connid_.IsDefault()) {
          _this->_internal_set_connid("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (!from._internal_action().empty()) {
        _this->_internal_set_action(from._internal_action());
      } else {
        if (_this->_impl_.action_.IsDefault()) {
          _this->_internal_set_action("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (!from._internal_appid().empty()) {
        _this->_internal_set_appid(from._internal_appid());
      } else {
        if (_this->_impl_.appid_.IsDefault()) {
          _this->_internal_set_appid("");
        }
      }
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      if (!from._internal_msg().empty()) {
        _this->_internal_set_msg(from._internal_msg());
      } else {
        if (_this->_impl_.msg_.IsDefault()) {
          _this->_internal_set_msg("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PackMessage::CopyFrom(const PackMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wsg.gateway.protocol.PackMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PackMessage::InternalSwap(PackMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.wsgid_, &other->_impl_.wsgid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.connid_, &other->_impl_.connid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_, &other->_impl_.action_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.appid_, &other->_impl_.appid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
}

::google::protobuf::Metadata PackMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace gateway
}  // namespace wsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protocol_5fmessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
